/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_StringJNI */

#ifndef _Included_com_example_jni_StringJNI
#define _Included_com_example_jni_StringJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_StringJNI
 * Method:    processString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_StringJNI_processString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
