/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_StructJNI */

#ifndef _Included_com_example_jni_StructJNI
#define _Included_com_example_jni_StructJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_StructJNI
 * Method:    printPerson
 * Signature: (Lcom/example/jni/Person;)V
 */
JNIEXPORT void JNICALL Java_com_example_jni_StructJNI_printPerson
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
