/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_ArrayJNI */

#ifndef _Included_com_example_jni_ArrayJNI
#define _Included_com_example_jni_ArrayJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_ArrayJNI
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_ArrayJNI_sumArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
